pacman-vendor-file $ added to prevent pattern match extra files

diff --git a/expac/.local/bin/pacman-vendor-file b/expac/.local/bin/pacman-vendor-file
--- a/expac/.local/bin/pacman-vendor-file
+++ b/expac/.local/bin/pacman-vendor-file
@@ -66,5 +66,5 @@ else
     PKG_TAR="/var/cache/pacman/pkg/${PKG_FILENAME}"
 fi
 
-RES=$(bsdtar --extract --to-stdout --file "$PKG_TAR" ."${FILE}") || { echo "Error extract"; exit 1; }
+RES=$(bsdtar --extract --to-stdout --file "$PKG_TAR" ."${FILE}"$) || { echo "Error extract"; exit 1; }
 echo "$RES"
