pacman files

diff --git a/expac/.local/bin/pacman-vendor-file b/expac/.local/bin/pacman-vendor-file
--- a/expac/.local/bin/pacman-vendor-file
+++ b/expac/.local/bin/pacman-vendor-file
@@ -2,12 +2,12 @@
 
 # Вывести исходное содержимое файла
 
-function usage() {
+usage() {
     echo "Usage: $0 [-h|--help] <file>"
     echo "  -h, --help         Display this help message"
 }
 
-function canonicalPath {
+canonicalPath() {
     local path="$1" ; shift
     if [ -d "$path" ]; then
         echo "$(cd "$path" || exit ; pwd)"
@@ -18,6 +18,11 @@ function canonicalPath {
         p=$(dirname "$path")
         echo "$(cd "$p" || exit ; pwd)/$b"
     fi
+}
+
+is_aur_package() {
+    local pkg_name="$1"; shift
+    pacman --query --foreign --color never "$pkg_name"
 }
 
 # Parse command-line arguments
@@ -45,14 +50,20 @@ if [[ ! -f "$FILE" ]]; then
     exit 0
 fi
 
-#пакет
-PKG_NAME=$(pacman -Qqo --color never "$FILE") || { echo "Error get package"; exit 1; }
+# пакет
+PKG_NAME=$(pacman --query --quiet --owns --color never "$FILE") || { echo "Error get package"; exit 1; }
 
-#архитектура версия
-PKG_ARCH=$(expac -Q '%a' "$PKG_NAME") || { echo "Error get arch"; exit 1; }
-PKG_VER=$(expac -Q '%v' "$PKG_NAME") || { echo "Error get ver"; exit 1; }
+# архитектура версия
+PKG_ARCH=$(expac --query '%a' "$PKG_NAME") || { echo "Error get arch"; exit 1; }
+PKG_VER=$(expac --query '%v' "$PKG_NAME") || { echo "Error get ver"; exit 1; }
 
-PKG_TAR="/var/cache/pacman/pkg/${PKG_NAME}-${PKG_VER}-${PKG_ARCH}.pkg.tar.zst"
+# из AUR или нет
+IS_AUR=$(is_aur_package "$PKG_NAME")
+if [[ -n "$IS_AUR" ]]; then
+    PKG_TAR="${HOME}/.cache/yay/${PKG_NAME}/${PKG_NAME}-${PKG_VER}-${PKG_ARCH}.pkg.tar.zst"
+else
+    PKG_TAR="/var/cache/pacman/pkg/${PKG_NAME}-${PKG_VER}-${PKG_ARCH}.pkg.tar.zst"
+fi
 
 RES=$(bsdtar --extract --to-stdout --file "$PKG_TAR" ."${FILE}") || { echo "Error extract"; exit 1; }
 echo "$RES"
